# Name of website
title: UFSIT Blue Team
description: follow the blue rabbit

# Your name to show in the footer
author: UFSIT

github:
  is_project_page: false

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
